### ISSUE TITLE
denormalization method

### ISSUE THREAD

**Issue by Martin1937** [nibtehaz/PPG2ABP#16]
Hi, thanks for the well written code. I have an issue with normalization and denormalization, it seems that min-max normalization is used to normalize the data in data_handling.py. However, when it comes to denormalization, the algorithm only multiplies by max_value then plus min_value, shouldn't it be multiply by (max_value - min_value) + min_value? Thanks :).

**Comment by Exuan148** [comment]
I have the same question.

**Comment by Exuan148** [comment]
> Hi, thanks for the well written code. I have an issue with normalization and denormalization, it seems that min-max normalization is used to normalize the data in data_handling.py. However, when it comes to denormalization, the algorithm only multiplies by max_value then plus min_value, shouldn't it be multiply by (max_value - min_value) + min_value? Thanks :).

Have you found the reason? Many thanks!

**Comment by Exuan148** [comment]
> Hi, thanks for the well written code. I have an issue with normalization and denormalization, it seems that min-max normalization is used to normalize the data in data_handling.py. However, when it comes to denormalization, the algorithm only multiplies by max_value then plus min_value, shouldn't it be multiply by (max_value - min_value) + min_value? Thanks :).

Maybe he has a falsehood in the code, but the model's prediction performance is still good

**Comment by nibtehaz** [comment]
Sorry for not seeing this earlier. I apologize for this. It appears that it was a bug in our code and this led to selecting a cross-validation model that followed that constraint. At the end the result was still the same (and satisfactorily) but achieved a bit differently. It is not the correct way to achieve this, but unfortunately this bug was overlooked. I hope the readers will pardon me, this is something I did in very early part of my career and I was just learning things that time.

**Comment by Exuan148** [comment]
> Sorry for not seeing this earlier. I apologize for this. It appears that it was a bug in our code and this led to selecting a cross-validation model that followed that constraint. At the end the result was still the same (and satisfactorily) but achieved a bit differently. It is not the correct way to achieve this, but unfortunately this bug was overlooked. I hope the readers will pardon me, this is something I did in very early part of my career and I was just learning things that time.

No problem. Respect!

**Comment by HzO-py** [comment]
hi

**Comment by HzO-py** [comment]
SBP error should be (max_value - min_value)*abs(Y_pred-Y_real) instead of max_value*abs(Y_pred-Y_real)
So isn't the result better if you use the correct formula?

**Comment by Exuan148** [comment]
Yes.












HAN&nbsp;YIXUAN
***@***.***

National&nbsp;U.&nbsp;of&nbsp;Singapore




---Original---
From: ***@***.***&gt;
Date: Thu, Nov 28, 2024 16:24 PM
To: ***@***.***&gt;;
Cc: "Han ***@***.******@***.***&gt;;
Subject: Re: [nibtehaz/PPG2ABP] denormalization method (Issue #16)




 
SBP error should be (max_value - min_value)abs(Y_pred-Y_real) instead of max_valueabs(Y_pred-Y_real)
 So isn't the result better if you use the correct formula?
